// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         feature_code: "feature_code",
 *         subject_id: "subject_id"
 *     }
 */
export interface CheckRequest {
    feature_code: string;
    subject_id: string;
}
