// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         plan_key: "plan_key"
 *     }
 */
export interface ChangePlanRequest {
    /** The plan key to switch to. */
    plan_key: string;
}
