// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subject_id: "subject_id"
 *     }
 */
export interface CreatePortalTokenRequest {
    /** The subject (end user) to generate a portal token for. */
    subject_id: string;
}
