// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PortalListInvoicesRequest {
    /** Maximum number of items to return per page. */
    limit?: number | null;
    /** Opaque pagination cursor from a previous response's `next_cursor` field. */
    cursor?: string | null;
}
