// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateKeyRequest {
    /** Human-readable name for the key (e.g., "Production", "Staging"). */
    name: string;
}
