// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         key_id: "key_id"
 *     }
 */
export interface DeleteKeyRequest {
    /** The key identifier to revoke */
    key_id: string;
}
