// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace SchemaClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Upload, validate, and retrieve your entitlement schema
 */
export class SchemaClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SchemaClient.Options>;

    constructor(options: SchemaClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieves the tenant's own schema document from the store.
     * Tenant is resolved from `X-Api-Key` via the auth middleware.
     *
     * - If the tenant has a schema: returns 200 with the schema document body (as stored).
     * - If the tenant has no schema: returns 404 with `{ "error": "schema not found" }`.
     * - If a store error occurs: returns 500 with `{ "error": "internal error" }`.
     *
     * @param {SchemaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.schema.getSchema()
     */
    public getSchema(requestOptions?: SchemaClient.RequestOptions): core.HttpResponsePromise<string> {
        return core.HttpResponsePromise.fromPromise(this.__getSchema(requestOptions));
    }

    private async __getSchema(requestOptions?: SchemaClient.RequestOptions): Promise<core.WithRawResponse<string>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "schema",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "text",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as string, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/schema");
    }

    /**
     * Validates, persists to store, and invalidates all tenant cache entries.
     * Tenant is resolved from `X-Api-Key` via the auth middleware.
     *
     * - If the body is empty: returns 400.
     * - If the document has validation errors: returns 200 with `{ "valid": false, "errors": [...] }` (not persisted).
     * - If the document is valid: persists to store, invalidates cache, returns 200 with `{ "valid": true, "errors": [] }`.
     * - If a store or cache error occurs: returns 500.
     *
     * @param {SchemaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.schema.putSchema()
     */
    public putSchema(
        requestOptions?: SchemaClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.ValidationErrorResponse> {
        return core.HttpResponsePromise.fromPromise(this.__putSchema(requestOptions));
    }

    private async __putSchema(
        requestOptions?: SchemaClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.ValidationErrorResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "schema",
            ),
            method: "PUT",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.ValidationErrorResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/schema");
    }

    /**
     * Accepts a raw schema document body (YAML or JSON), runs the full validator
     * (structural + semantic), and returns a `ValidationErrorResponse` without
     * persisting anything.
     *
     * - If the document is valid: returns 200 with `{ "valid": true, "errors": [] }`.
     * - If the document has validation errors: returns 200 with `{ "valid": false, "errors": [...] }`.
     * - If the body is empty: returns 400.
     *
     * This endpoint is protected by the auth middleware (X-Api-Key), but does not
     * use the tenant context since validation is stateless.
     *
     * @param {SchemaClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.schema.validateSchema()
     */
    public validateSchema(
        requestOptions?: SchemaClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.ValidationErrorResponse> {
        return core.HttpResponsePromise.fromPromise(this.__validateSchema(requestOptions));
    }

    private async __validateSchema(
        requestOptions?: SchemaClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.ValidationErrorResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "schema/validate",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.ValidationErrorResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/schema/validate");
    }
}
