// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface GetUsageRequest {
    /** When true, returns per-subject usage breakdowns */
    per_subject?: boolean;
}
