// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subject_id: "subject_id",
 *         feature_code: "feature_code",
 *         value: 1000000
 *     }
 */
export interface SetUsageRequest {
    /** The subject whose counter is being set */
    subject_id: string;
    /** The stateful feature code (e.g., "seats") */
    feature_code: string;
    /** The absolute counter value to set. */
    value: number;
}
