// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         plan_key: "plan_key",
 *         subject_id: "subject_id"
 *     }
 */
export interface CreateAssignmentRequest {
    plan_key: string;
    subject_id: string;
}
