// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subject_id: "subject_id"
 *     }
 */
export interface DeleteAssignmentRequest {
    /** The subject identifier to unassign */
    subject_id: string;
}
