// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface GetSchemaRequest {
    /** Output format: "json" (default) or "yaml". */
    format?: BillkitApi.GetSchemaRequestFormat | null;
}
