// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PutSchemaRequest {
    /**
     * When `true`, bypass the referential-integrity check against existing
     * subject assignments and persist the schema even if doing so would orphan
     * a plan, contract, or add-on key that subjects are still assigned to.
     * Defaults to `false`.
     */
    force?: boolean | null;
}
