// This file was auto-generated by Fern from our API Definition.

/** Add-on type: must match the target feature's type. */
export const AddonType = {
    MeteredModifier: "metered_modifier",
    StatefulModifier: "stateful_modifier",
} as const;
export type AddonType = (typeof AddonType)[keyof typeof AddonType];
