// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Add-on definition that can increase limits for features.
 */
export interface AddonDefinition {
    increase_by: number;
    target: string;
    type: BillkitApi.AddonType;
}
