// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for a successful contract application.
 */
export interface ApplyContractResponse {
    contract_key: string;
    subject_id: string;
}
