// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for a successful add-on attachment.
 */
export interface AttachAddonResponse {
    addon_key: string;
    addons: string[];
    subject_id: string;
}
