// This file was auto-generated by Fern from our API Definition.

/** Data type for attribute features. */
export const AttributeDataType = {
    Integer: "integer",
    String: "string",
    Boolean: "boolean",
} as const;
export type AttributeDataType = (typeof AttributeDataType)[keyof typeof AttributeDataType];
