// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for `POST /subjects/batch`.
 */
export interface BatchRegisterResponse {
    results: BillkitApi.BatchSubjectResult[];
}
