// This file was auto-generated by Fern from our API Definition.

/**
 * A single result in the batch response.
 */
export interface BatchSubjectResult {
    billing_status: string;
    error?: (string | null) | undefined;
    stripe_customer_id?: (string | null) | undefined;
    subject_id: string;
}
