// This file was auto-generated by Fern from our API Definition.

/** Billing cycle frequency for invoice generation. */
export const BillingCycle = {
    Monthly: "monthly",
    Yearly: "yearly",
} as const;
export type BillingCycle = (typeof BillingCycle)[keyof typeof BillingCycle];
