// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Billing configuration for a schema, enabling invoicing features.
 */
export interface BillingConfig {
    /** How often invoices are generated */
    billing_cycle: BillkitApi.BillingCycle;
    /** ISO 4217 currency code (e.g., "USD", "EUR", "GBP") */
    currency: string;
    /** Number of grace days before delinquency enforcement kicks in */
    delinquency_grace_days?: (number | null) | undefined;
    /** Whether to deny access when a subject is delinquent */
    deny_on_delinquency?: (boolean | null) | undefined;
    /** Whether subjects must have a payment method on file */
    require_autopay?: (boolean | null) | undefined;
}
