// This file was auto-generated by Fern from our API Definition.

/** Reset cadence for metered feature counters. */
export const Cadence = {
    Hourly: "hourly",
    Daily: "daily",
    Monthly: "monthly",
    Yearly: "yearly",
} as const;
export type Cadence = (typeof Cadence)[keyof typeof Cadence];
