// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for a successful plan change.
 */
export interface ChangePlanResponse {
    /** ISO 8601 timestamp of when the change was recorded. */
    changed_at: string;
    /** "immediate" for upgrades and lateral/no-billing changes, "next_cycle" for downgrades. */
    effective: string;
    /** The plan the subject is now on (or will be on at next cycle). */
    new_plan_key: string;
    /** The plan the subject was on before the change. */
    previous_plan_key: string;
    /** Amount immediately charged for upgrade proration, in cents. 0 if none was charged. */
    proration_charge_cents: number;
    /** The subject whose plan was changed. */
    subject_id: string;
}
