// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Custom contract that overrides plan entitlements for a specific subject.
 */
export interface ContractDefinition {
    inherits: string;
    overrides: BillkitApi.PlanDefinition;
}
