// This file was auto-generated by Fern from our API Definition.

/**
 * Response body after creating a new API key (shows the full key once).
 */
export interface CreateKeyResponse {
    api_key: string;
    created_at: string;
    key_id: string;
    message: string;
    name: string;
    prefix: string;
}
