// This file was auto-generated by Fern from our API Definition.

/**
 * Successful response for `POST /billing/portal-token`.
 */
export interface CreatePortalTokenResponse {
    /** Token expiration time (ISO 8601). */
    expires_at: string;
    /** The full portal URL the end user should be redirected to. */
    portal_url: string;
    /** The signed JWT token. */
    token: string;
}
