// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for a successful assignment.
 */
export interface CreateAssignmentResponse {
    assigned_at: string;
    plan_key: string;
    subject_id: string;
}
