// This file was auto-generated by Fern from our API Definition.

/** Gate decision outcome. */
export const Decision = {
    Allowed: "allowed",
    Denied: "denied",
    NoPlan: "no_plan",
} as const;
export type Decision = (typeof Decision)[keyof typeof Decision];
