// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * The value of a feature for a specific plan.
 */
export interface FeatureValue {
    display: string;
    included: boolean;
    overage?: (BillkitApi.OverageInfo | null) | undefined;
    raw?: unknown | undefined;
}
