// This file was auto-generated by Fern from our API Definition.

/**
 * A single feature's usage statistics in the response.
 */
export interface FeatureUsage {
    /**
     * Cumulative usage across all cadence windows in the current billing period.
     * Only present when the tenant has a billing configuration.
     */
    billing_period_usage?: (number | null) | undefined;
    /** The cadence window (e.g., "monthly", "daily") if applicable. */
    cadence?: (string | null) | undefined;
    /** The feature code (key in the schema features map). */
    feature_code: string;
    /** The feature type (metered, stateful, boolean, attribute). */
    feature_type: string;
    /** The plan limit for this feature (null if unlimited or not applicable). */
    limit?: (number | null) | undefined;
    /** The overage policy ("block" or "soft") if applicable. */
    overage?: (string | null) | undefined;
    /** When the counter will next reset (ISO 8601, equal to window_end). Only present for metered features with a cadence. */
    resets_at?: (string | null) | undefined;
    /** Total consumption across all subjects for this feature in the current cadence window. */
    total_usage: number;
    /** Whether usage exceeds 80% of the limit (warning threshold). */
    warning: boolean;
    /** End of the current cadence window (ISO 8601). Only present for metered features with a cadence. */
    window_end?: (string | null) | undefined;
    /** Start of the current cadence window (ISO 8601). Only present for metered features with a cadence. */
    window_start?: (string | null) | undefined;
}
