// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Definition of a single feature in the entitlement schema.
 */
export interface FeatureDefinition {
    data_type?: (BillkitApi.AttributeDataType | null) | undefined;
    type: BillkitApi.FeatureType;
}
