// This file was auto-generated by Fern from our API Definition.

/** The type of a feature determines how gate decisions are evaluated. */
export const FeatureType = {
    Boolean: "boolean",
    Metered: "metered",
    Stateful: "stateful",
    Attribute: "attribute",
} as const;
export type FeatureType = (typeof FeatureType)[keyof typeof FeatureType];
