// This file was auto-generated by Fern from our API Definition.

/**
 * A single feature's usage statistics in the aggregated response.
 *
 * Plan-specific fields (limit, cadence, overage, warning) are intentionally
 * omitted from the aggregated view because they are per-plan and cannot be
 * meaningfully resolved at the tenant level. Use `?per_subject=true` for
 * per-subject usage with plan-specific limits.
 */
export interface FeatureUsage {
    /**
     * Cumulative usage across all cadence windows in the current billing period.
     * Only present when the tenant has a billing configuration.
     */
    billing_period_usage?: (number | null) | undefined;
    /** The feature code (key in the schema features map). */
    feature_code: string;
    /** The feature type (metered, stateful, boolean, attribute). */
    feature_type: string;
    /** When the counter will next reset (ISO 8601, equal to window_end). Only present for metered features with a cadence. */
    resets_at?: (string | null) | undefined;
    /** Total consumption across all subjects for this feature in the current cadence window. */
    total_usage: number;
    /** End of the current cadence window (ISO 8601). Only present for metered features with a cadence. */
    window_end?: (string | null) | undefined;
    /** Start of the current cadence window (ISO 8601). Only present for metered features with a cadence. */
    window_start?: (string | null) | undefined;
}
