// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response returned by the `POST /check` endpoint.
 */
export interface GateResponse {
    attribute_value?: unknown | undefined;
    decision: BillkitApi.Decision;
    overage?: (boolean | null) | undefined;
    reason?: (string | null) | undefined;
}
