// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * A single invoice in the list response.
 */
export interface InvoiceListItem {
    amount_cents: number;
    billing_period_end: string;
    billing_period_start: string;
    created_at: string;
    currency: string;
    invoice_id: string;
    line_items: BillkitApi.InvoiceLineItemResponse[];
    paid_at?: (string | null) | undefined;
    status: string;
    stripe_invoice_id: string;
    subject_id: string;
}
