// This file was auto-generated by Fern from our API Definition.

/**
 * A single invoice-failure marker in the list response.
 */
export interface InvoiceFailureItem {
    attempt_count: number;
    error: string;
    exhausted: boolean;
    first_failed_at: string;
    last_failed_at: string;
    subject_id: string;
    window_end: string;
    window_start: string;
}
