// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for `GET /invoices/:subject_id/preview`.
 */
export interface InvoicePreviewResponse {
    base_price_cents: number;
    currency: string;
    line_items: BillkitApi.InvoiceLineItemResponse[];
    overage_items: BillkitApi.PreviewOverageItem[];
    plan_key: string;
    subject_id: string;
    total_cents: number;
}
