// This file was auto-generated by Fern from our API Definition.

/**
 * Line item in the invoice response.
 */
export interface InvoiceLineItemResponse {
    amount_cents: number;
    description: string;
}
