// This file was auto-generated by Fern from our API Definition.

/**
 * A single API key in the list response (key is masked).
 */
export interface KeyListItem {
    created_at: string;
    key_id: string;
    last_used_at?: (string | null) | undefined;
    name: string;
    prefix: string;
}
