// This file was auto-generated by Fern from our API Definition.

/**
 * A positive integer or the string "unlimited"
 */
export type Limit =
    /**
     * A positive integer limit */
    | number
    /**
     * Unlimited access */
    | "unlimited";
