// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Limit definition for a metered or stateful feature within a plan.
 */
export interface LimitDefinition {
    cadence?: (BillkitApi.Cadence | null) | undefined;
    max: BillkitApi.Limit;
    overage?: (BillkitApi.OveragePolicy | null) | undefined;
    overage_unit_price?: (number | null) | undefined;
}
