// This file was auto-generated by Fern from our API Definition.

/**
 * Query parameters for `GET /invoices`.
 */
export interface ListInvoicesParams {
    /** Filter: only include invoices with billing_period_start <= end_date. */
    end_date?: (string | null) | undefined;
    /** Filter: only include invoices with billing_period_end >= start_date. */
    start_date?: (string | null) | undefined;
    /** Filter by invoice status (e.g., "open", "paid", "past_due", "uncollectible"). */
    status?: (string | null) | undefined;
    /** Filter by subject ID. */
    subject_id?: (string | null) | undefined;
}
