// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for listing API keys.
 */
export interface ListKeysResponse {
    keys: BillkitApi.KeyListItem[];
}
