// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for `GET /invoices/platform`.
 */
export interface ListPlatformInvoicesResponse {
    /** List of platform invoices, sorted by created_at descending. */
    invoices: BillkitApi.PlatformInvoiceItem[];
}
