// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for `GET /invoice-failures`.
 */
export interface ListInvoiceFailuresResponse {
    failures: BillkitApi.InvoiceFailureItem[];
    /** Whether more results exist beyond this page. */
    has_more: boolean;
    /** Opaque cursor for the next page. Null/absent on the last page. */
    next_cursor?: (string | null) | undefined;
}
