// This file was auto-generated by Fern from our API Definition.

/**
 * Query parameters for `GET /invoice-failures`.
 */
export interface ListInvoiceFailuresParams {
    /** Pagination: opaque cursor from a previous response's `next_cursor` field. */
    cursor?: (string | null) | undefined;
    /**
     * Filter by whether the retry budget is exhausted. When omitted, both
     * retryable and exhausted markers are returned.
     */
    exhausted?: (boolean | null) | undefined;
    /** Pagination: maximum number of items to return per page (1–1000, default 100). */
    limit?: (number | null) | undefined;
    /** Filter by subject ID. */
    subject_id?: (string | null) | undefined;
}
