// This file was auto-generated by Fern from our API Definition.

/**
 * Monthly revenue breakdown entry.
 */
export interface MonthlyRevenue {
    /** Sum of `amount_cents` for invoices with status "paid" in this month. */
    collected_cents: number;
    /** Total number of invoices in this month (regardless of status). */
    invoice_count: number;
    /** Month in YYYY-MM format (derived from `billing_period_end`). */
    month: string;
    /** Sum of `amount_cents` for invoices with status "open" or "past_due" in this month. */
    outstanding_cents: number;
}
