// This file was auto-generated by Fern from our API Definition.

/**
 * Overage pricing information for a metered feature.
 */
export interface OverageInfo {
    unit_price_cents: number;
    unit_price_display: string;
}
