// This file was auto-generated by Fern from our API Definition.

/** Enforcement behavior when a metered limit is reached. */
export const OveragePolicy = {
    Block: "block",
    Soft: "soft",
    Billed: "billed",
} as const;
export type OveragePolicy = (typeof OveragePolicy)[keyof typeof OveragePolicy];
