// This file was auto-generated by Fern from our API Definition.

/**
 * Query parameters for paginated list endpoints.
 */
export interface PaginationQuery {
    /** Opaque pagination cursor from a previous response's `next_cursor` field. */
    cursor?: (string | null) | undefined;
    /** Maximum number of items to return per page. */
    limit?: (number | null) | undefined;
}
