// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Plan definition within a schema.
 */
export interface PlanDefinition {
    attributes?: (Record<string, unknown> | null) | undefined;
    display_name?: (string | null) | undefined;
    grants?: (Record<string, boolean | null> | null) | undefined;
    inherits?: (string | null) | undefined;
    limits?: (Record<string, BillkitApi.LimitDefinition | null> | null) | undefined;
    price?: (number | null) | undefined;
}
