// This file was auto-generated by Fern from our API Definition.

/**
 * A single platform invoice item in the response.
 */
export interface PlatformInvoiceItem {
    /** Total amount in cents. */
    amount_cents: number;
    /** RFC 3339 timestamp of when the invoice was created. */
    created_at: string;
    /** Stripe invoice ID. */
    id: string;
    /** URL to the PDF version of the invoice (currently not available). */
    pdf_url?: (string | null) | undefined;
    /** Invoice status (e.g. "paid", "open"). */
    status: string;
}
