// This file was auto-generated by Fern from our API Definition.

/**
 * A single overage line item in the preview response.
 */
export interface PreviewOverageItem {
    amount_cents: number;
    feature_code: string;
    limit: number;
    overage_units: number;
    unit_price_cents: number;
    usage: number;
}
