// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata about the pricing response.
 */
export interface PricingMetadata {
    generated_at: string;
    schema_version: string;
}
