// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Top-level pricing response returned by `GET /pricing`.
 */
export interface PricingResponse {
    billing?: (BillkitApi.PricingBilling | null) | undefined;
    features: BillkitApi.PricingFeature[];
    metadata: BillkitApi.PricingMetadata;
    plans: BillkitApi.PricingPlan[];
    rate_card?: (BillkitApi.RateCardResponse | null) | undefined;
}
