// This file was auto-generated by Fern from our API Definition.

/**
 * A feature definition for the pricing page feature comparison rows.
 */
export interface PricingFeature {
    code: string;
    display_name: string;
    type: string;
}
