// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * A single plan formatted for pricing page display.
 */
export interface PricingPlan {
    display_name: string;
    feature_values: Record<string, BillkitApi.FeatureValue>;
    key: string;
    price: number;
    price_display: string;
}
