// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Rate card response (only included for the system tenant).
 */
export interface RateCardResponse {
    dimensions: BillkitApi.RateCardDimension[];
}
