// This file was auto-generated by Fern from our API Definition.

/**
 * A single dimension of the platform rate card.
 */
export interface RateCardDimension {
    code: string;
    display_name: string;
    free_tier: number;
    free_tier_display: string;
    unit_price_cents: number;
    unit_price_display: string;
    unit_size: number;
}
