// This file was auto-generated by Fern from our API Definition.

/**
 * Request body for `POST /subjects`.
 */
export interface RegisterSubjectRequest {
    /** Email address for the subject (required for invoicing). */
    email?: (string | null) | undefined;
    /** Display name for the subject. */
    name?: (string | null) | undefined;
    /** Plan key to assign (defaults to tenant's default plan if unset). */
    plan_key?: (string | null) | undefined;
    subject_id: string;
}
