// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for `POST /subjects`.
 */
export interface RegisterSubjectResponse {
    billing_status: string;
    email?: (string | null) | undefined;
    name?: (string | null) | undefined;
    plan_key: string;
    stripe_customer_id?: (string | null) | undefined;
    subject_id: string;
}
