// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for `GET /invoices/revenue`.
 */
export interface RevenueResponse {
    /** Per-month breakdown, sorted chronologically (oldest first). */
    month_over_month: BillkitApi.MonthlyRevenue[];
    /** Sum of `amount_cents` for all invoices with status "paid". */
    total_collected_cents: number;
    /** Sum of `amount_cents` across all invoices. */
    total_invoiced_cents: number;
    /**
     * Sum of `amount_cents` for all invoices whose status is outstanding
     * (money still owed): "open", "past_due", or "payment_failed".
     */
    total_outstanding_cents: number;
}
