// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for a successful key rotation.
 */
export interface RotateKeyResponse {
    api_key: string;
    message: string;
}
