// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Top-level schema document uploaded by tenants.
 */
export interface SchemaDocument {
    addons?: (Record<string, BillkitApi.AddonDefinition | null> | null) | undefined;
    billing?: (BillkitApi.BillingConfig | null) | undefined;
    custom_contracts?: (Record<string, BillkitApi.ContractDefinition | null> | null) | undefined;
    default_plan?: (string | null) | undefined;
    features: Record<string, BillkitApi.FeatureDefinition>;
    plans: Record<string, BillkitApi.PlanDefinition>;
    version: string;
}
