// This file was auto-generated by Fern from our API Definition.

/**
 * Rejection response for `PUT /subjects/{subject_id}/usage/{feature_code}` (409).
 */
export interface SetUsageRejection {
    /** Always `false` for a rejected set. */
    accepted: boolean;
    /** The current counter value (if available). */
    current_value?: (number | null) | undefined;
    /** The effective limit for this feature (if applicable). */
    max?: (number | null) | undefined;
    /** Human-readable reason for the rejection. */
    reason: string;
    /** The value that was requested (if applicable). */
    requested_value?: (number | null) | undefined;
}
