// This file was auto-generated by Fern from our API Definition.

/**
 * Successful response for `PUT /subjects/{subject_id}/usage/{feature_code}`.
 */
export interface SetUsageResponse {
    /** Always `true` for a successful set. */
    accepted: boolean;
    /** The effective limit for this feature, if applicable. */
    max?: (number | null) | undefined;
    /** The counter value after this write (equals the requested value). */
    new_value: number;
    /** The counter value before this write. */
    previous_value: number;
}
