// This file was auto-generated by Fern from our API Definition.

/**
 * A single subject's info in the list response.
 */
export interface SubjectInfo {
    addons: string[];
    assigned_at: string;
    contract_key?: (string | null) | undefined;
    plan_key: string;
    subject_id: string;
}
