// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for `GET /subjects/:subject_id`.
 */
export interface SubjectDetailResponse {
    addons: string[];
    assigned_at: string;
    billing_status: string;
    contract_key?: (string | null) | undefined;
    email?: (string | null) | undefined;
    name?: (string | null) | undefined;
    payment_method_status: string;
    plan_key: string;
    stripe_customer_id?: (string | null) | undefined;
    subject_id: string;
}
