// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for `GET /subjects`.
 */
export interface SubjectsResponse {
    subjects: BillkitApi.SubjectInfo[];
}
