// This file was auto-generated by Fern from our API Definition.

/**
 * Response body for `GET /tenants/me`.
 */
export interface TenantMeResponse {
    created_at: string;
    org_id: string;
    plan_key: string;
    tenant_id: string;
}
