// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for `GET /usage`.
 */
export interface UsageResponse {
    /** End of the current billing period (ISO 8601). Only present when billing is configured. */
    billing_period_end?: (string | null) | undefined;
    /** Start of the current billing period (ISO 8601). Only present when billing is configured. */
    billing_period_start?: (string | null) | undefined;
    features: BillkitApi.FeatureUsage[];
    /** Total API calls across all metered features. */
    total_api_calls: number;
}
