// This file was auto-generated by Fern from our API Definition.

/**
 * Validation error returned when a schema fails validation.
 */
export interface ValidationError {
    field: string;
    message: string;
}
