// This file was auto-generated by Fern from our API Definition.

/**
 * Validation warning — informational issue that does not prevent schema acceptance.
 */
export interface ValidationWarning {
    field: string;
    message: string;
}
