// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../index.js";

/**
 * Response body for validation endpoints.
 */
export interface ValidationErrorResponse {
    errors?: BillkitApi.ValidationError[] | undefined;
    valid: boolean;
}
