// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace InvoicesClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Invoice listing and preview
 */
export class InvoicesClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<InvoicesClient.Options>;

    constructor(options: InvoicesClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists end-user invoices for the authenticated tenant with optional filtering
     * by subject_id, status, and date range.
     *
     * Query parameters:
     * - `subject_id` — filter by subject
     * - `status` — filter by invoice status (open, paid, past_due, uncollectible)
     * - `start_date` — ISO 8601 datetime; only invoices overlapping this date or later
     * - `end_date` — ISO 8601 datetime; only invoices overlapping this date or earlier
     *
     * @param {BillkitApi.ListInvoicesRequest} request
     * @param {InvoicesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.invoices.listInvoices()
     */
    public listInvoices(
        request: BillkitApi.ListInvoicesRequest = {},
        requestOptions?: InvoicesClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.ListInvoicesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listInvoices(request, requestOptions));
    }

    private async __listInvoices(
        request: BillkitApi.ListInvoicesRequest = {},
        requestOptions?: InvoicesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.ListInvoicesResponse>> {
        const { subject_id: subjectId, status, start_date: startDate, end_date: endDate } = request;
        const _queryParams: Record<string, unknown> = {
            subject_id: subjectId,
            status,
            start_date: startDate,
            end_date: endDate,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "invoices",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.ListInvoicesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/invoices");
    }

    /**
     * Calculates what the next invoice would look like for a subject based on
     * their current usage, plan assignment, and schema billing configuration.
     *
     * Returns:
     * - 200 with the preview if billable usage exists
     * - 404 if the subject is not found or has no plan assignment
     * - 422 if no billing config or Connect account is configured
     *
     * @param {BillkitApi.PreviewInvoiceRequest} request
     * @param {InvoicesClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.UnprocessableEntityError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.invoices.previewInvoice({
     *         subject_id: "subject_id"
     *     })
     */
    public previewInvoice(
        request: BillkitApi.PreviewInvoiceRequest,
        requestOptions?: InvoicesClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.InvoicePreviewResponse> {
        return core.HttpResponsePromise.fromPromise(this.__previewInvoice(request, requestOptions));
    }

    private async __previewInvoice(
        request: BillkitApi.PreviewInvoiceRequest,
        requestOptions?: InvoicesClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.InvoicePreviewResponse>> {
        const { subject_id: subjectId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `invoices/${core.url.encodePathParam(subjectId)}/preview`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.InvoicePreviewResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BillkitApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/invoices/{subject_id}/preview",
        );
    }
}
