// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         addon_key: "addon_key",
 *         subject_id: "subject_id"
 *     }
 */
export interface AttachAddonRequest {
    addon_key: string;
    subject_id: string;
}
