// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subject_id: "subject_id",
 *         addon_key: "addon_key"
 *     }
 */
export interface DetachAddonRequest {
    /** The subject identifier */
    subject_id: string;
    /** The add-on key to detach */
    addon_key: string;
}
