// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace ApiKeysClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Manage API keys for programmatic access
 */
export class ApiKeysClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<ApiKeysClient.Options>;

    constructor(options: ApiKeysClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Lists all named API keys for the tenant. Keys are masked (only prefix shown).
     *
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.apiKeys.listKeys()
     */
    public listKeys(
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.ListKeysResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listKeys(requestOptions));
    }

    private async __listKeys(
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.ListKeysResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "keys",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.ListKeysResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/keys");
    }

    /**
     * Creates a new named API key for the tenant. The raw key value is returned
     * once in the response and never stored — only its SHA-256 hash is persisted.
     *
     * Limits tenants to MAX_KEYS_PER_TENANT keys.
     *
     * @param {BillkitApi.CreateKeyRequest} request
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.ConflictError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.apiKeys.createKey({
     *         name: "name"
     *     })
     */
    public createKey(
        request: BillkitApi.CreateKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.CreateKeyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createKey(request, requestOptions));
    }

    private async __createKey(
        request: BillkitApi.CreateKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.CreateKeyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "keys",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.CreateKeyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new BillkitApi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/keys");
    }

    /**
     * Generates a new API key, updates the tenant record in the store, replaces
     * the API key reference, updates cache mappings, and invalidates the old key.
     * After rotation, the old key will be rejected with 401 on subsequent requests.
     *
     * - If the tenant record cannot be found: returns 500 (should not happen since
     *   auth middleware already resolved the tenant).
     * - If a store or cache error occurs: returns 500.
     * - On success: returns 200 with the new API key (shown only once).
     *
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.apiKeys.rotateKey()
     */
    public rotateKey(
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.RotateKeyResponse> {
        return core.HttpResponsePromise.fromPromise(this.__rotateKey(requestOptions));
    }

    private async __rotateKey(
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.RotateKeyResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "keys/rotate",
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.RotateKeyResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/keys/rotate");
    }

    /**
     * Revokes (deletes) a specific API key by its key_id. Removes both the
     * tenant-scoped record and the global API key reference, and invalidates
     * the key in cache.
     *
     * @param {BillkitApi.DeleteKeyRequest} request
     * @param {ApiKeysClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.apiKeys.deleteKey({
     *         key_id: "key_id"
     *     })
     */
    public deleteKey(
        request: BillkitApi.DeleteKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteKey(request, requestOptions));
    }

    private async __deleteKey(
        request: BillkitApi.DeleteKeyRequest,
        requestOptions?: ApiKeysClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { key_id: keyId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `keys/${core.url.encodePathParam(keyId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/keys/{key_id}");
    }
}
