// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace PricingClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Pricing page data — formatted entitlement schema for display
 */
export class PricingClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PricingClient.Options>;

    constructor(options: PricingClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns the authenticated tenant's pricing information formatted for a
     * pricing page. Plans are sorted by price ascending, features are ordered
     * by type (boolean → metered → stateful → attribute), and all values are
     * formatted for direct display.
     *
     * Supports conditional requests via `ETag` / `If-None-Match` headers.
     * Returns 304 Not Modified when the schema has not changed.
     *
     * Responses are cached in Valkey with a 15-minute sliding TTL. Cache is
     * checked before DynamoDB to minimize latency for hot pricing pages.
     *
     * @param {PricingClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.pricing.getPricing()
     */
    public getPricing(
        requestOptions?: PricingClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.PricingResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getPricing(requestOptions));
    }

    private async __getPricing(
        requestOptions?: PricingClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.PricingResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "pricing",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.PricingResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/pricing");
    }
}
