// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace SubjectsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Register and manage subjects (end users / organizations)
 */
export class SubjectsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SubjectsClient.Options>;

    constructor(options: SubjectsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns all subject assignments for the authenticated tenant.
     * The tenant is resolved from `X-Api-Key` via the auth middleware.
     *
     * - If no subjects exist: returns HTTP 200 with an empty `subjects` array.
     * - If authenticated with the system API key: returns all subjects under the system tenant.
     * - If no valid API key is provided: returns HTTP 401 (handled by auth middleware).
     * - If a DynamoDB failure occurs: returns HTTP 500.
     *
     * @param {BillkitApi.ListSubjectsRequest} request
     * @param {SubjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.UnauthorizedError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.subjects.listSubjects()
     */
    public listSubjects(
        request: BillkitApi.ListSubjectsRequest = {},
        requestOptions?: SubjectsClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.SubjectsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSubjects(request, requestOptions));
    }

    private async __listSubjects(
        request: BillkitApi.ListSubjectsRequest = {},
        requestOptions?: SubjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.SubjectsResponse>> {
        const { limit, cursor } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            cursor,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "subjects",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.SubjectsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BillkitApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/subjects");
    }

    /**
     * Registers a subject with optional email and name. If an email is provided
     * and the tenant has an active Stripe Connect account, creates a Stripe Customer
     * on the connected account and marks the subject as "billable".
     *
     * If the subject already exists (re-registration), updates the Stripe Customer's
     * email/name rather than creating a duplicate.
     *
     * `plan_key` is validated against the tenant's schema, mirroring `POST /assignments`:
     * - If `plan_key` is provided but does not exist in the schema: returns 422.
     * - If `plan_key` is omitted, it defaults to the schema's `default_plan` (not the
     *   literal string `"free"`). If the schema defines no `default_plan`: returns 422.
     * - If the tenant has no schema uploaded at all: returns 422.
     *
     * - If subject_id is missing or too long: returns 400.
     * - If the subject already exists: updates email/name/plan_key/Stripe Customer (idempotent).
     * - If no Stripe Connect account is active: subject is stored without Stripe Customer.
     * - If Stripe API fails: returns 502 (subject is NOT partially created).
     * - On success: returns 201 (new) or 200 (re-registration).
     *
     * @param {BillkitApi.RegisterSubjectRequest} request
     * @param {SubjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.UnauthorizedError}
     * @throws {@link BillkitApi.UnprocessableEntityError}
     * @throws {@link BillkitApi.BadGatewayError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.subjects.registerSubject({
     *         subject_id: "subject_id"
     *     })
     */
    public registerSubject(
        request: BillkitApi.RegisterSubjectRequest,
        requestOptions?: SubjectsClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.RegisterSubjectResponse> {
        return core.HttpResponsePromise.fromPromise(this.__registerSubject(request, requestOptions));
    }

    private async __registerSubject(
        request: BillkitApi.RegisterSubjectRequest,
        requestOptions?: SubjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.RegisterSubjectResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "subjects",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.RegisterSubjectResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BillkitApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BillkitApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 502:
                    throw new BillkitApi.BadGatewayError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/subjects");
    }

    /**
     * Registers multiple subjects in a single request. Creates Stripe Customers
     * for each subject that has an email and where the tenant has active Connect.
     *
     * - If the batch exceeds 100 subjects: returns 400.
     * - Individual failures are reported per-subject (no rollback).
     * - On success: returns 200 with results array.
     *
     * @param {BillkitApi.BatchRegisterRequest} request
     * @param {SubjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.UnauthorizedError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.subjects.registerSubjectsBatch({
     *         subjects: [{
     *                 subject_id: "subject_id"
     *             }]
     *     })
     */
    public registerSubjectsBatch(
        request: BillkitApi.BatchRegisterRequest,
        requestOptions?: SubjectsClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.BatchRegisterResponse> {
        return core.HttpResponsePromise.fromPromise(this.__registerSubjectsBatch(request, requestOptions));
    }

    private async __registerSubjectsBatch(
        request: BillkitApi.BatchRegisterRequest,
        requestOptions?: SubjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.BatchRegisterResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "subjects/batch",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.BatchRegisterResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BillkitApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/subjects/batch");
    }

    /**
     * Returns a single subject's details including plan, billing status,
     * payment method status, and Stripe Customer ID.
     *
     * - If the subject does not exist: returns 404.
     * - On success: returns 200 with full subject details.
     *
     * @param {BillkitApi.GetSubjectRequest} request
     * @param {SubjectsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.UnauthorizedError}
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.subjects.getSubject({
     *         subject_id: "subject_id"
     *     })
     */
    public getSubject(
        request: BillkitApi.GetSubjectRequest,
        requestOptions?: SubjectsClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.SubjectDetailResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSubject(request, requestOptions));
    }

    private async __getSubject(
        request: BillkitApi.GetSubjectRequest,
        requestOptions?: SubjectsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.SubjectDetailResponse>> {
        const { subject_id: subjectId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `subjects/${core.url.encodePathParam(subjectId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.SubjectDetailResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new BillkitApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/subjects/{subject_id}");
    }
}
