// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace EntitlementsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Gate check endpoint — the hot path for entitlement decisions
 */
export class EntitlementsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<EntitlementsClient.Options>;

    constructor(options: EntitlementsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Authenticates via the auth middleware (X-Api-Key), resolves the entitlement
     * configuration from cache/store, invokes the gate decision evaluator, increments
     * the usage counter in cache for metered features, and returns a `GateResponse`.
     *
     * - If subject_id or feature_code is empty: returns 400.
     * - If feature_code not found in schema: returns 404.
     * - If subject has no plan assigned: returns 200 with `decision: "no_plan"`.
     * - If a store error occurs: returns 500.
     * - On success: returns 200 with the gate decision.
     *
     * @param {BillkitApi.CheckRequest} request
     * @param {EntitlementsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.entitlements.check({
     *         feature_code: "feature_code",
     *         subject_id: "subject_id"
     *     })
     */
    public check(
        request: BillkitApi.CheckRequest,
        requestOptions?: EntitlementsClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.GateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__check(request, requestOptions));
    }

    private async __check(
        request: BillkitApi.CheckRequest,
        requestOptions?: EntitlementsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.GateResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "check",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.GateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/check");
    }
}
