// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace AssignmentsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Assign plans to subjects
 */
export class AssignmentsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AssignmentsClient.Options>;

    constructor(options: AssignmentsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Assigns a plan to a subject. Validates that the plan key exists in the tenant's
     * schema, writes the assignment to the store, and invalidates the subject's cache entries.
     *
     * - If the request body is missing or malformed: returns 400.
     * - If the subject_id exceeds 256 characters: returns 400.
     * - If the tenant has no schema uploaded: returns 422.
     * - If the plan key does not exist in the schema: returns 422.
     * - If a store or cache error occurs: returns 500.
     * - On success: returns 201 with the assignment details.
     *
     * @param {BillkitApi.CreateAssignmentRequest} request
     * @param {AssignmentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.UnprocessableEntityError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.assignments.createAssignment({
     *         plan_key: "plan_key",
     *         subject_id: "subject_id"
     *     })
     */
    public createAssignment(
        request: BillkitApi.CreateAssignmentRequest,
        requestOptions?: AssignmentsClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.CreateAssignmentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createAssignment(request, requestOptions));
    }

    private async __createAssignment(
        request: BillkitApi.CreateAssignmentRequest,
        requestOptions?: AssignmentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.CreateAssignmentResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "assignments",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.CreateAssignmentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BillkitApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/assignments");
    }

    /**
     * Removes the subject assignment from the store and invalidates the subject's
     * cache entries. Tenant is resolved from `X-Api-Key` via the auth middleware.
     *
     * - If subject_id is empty: returns 400.
     * - If a store error occurs: returns 500.
     * - On success: returns 204 No Content (regardless of whether the assignment existed).
     *
     * @param {BillkitApi.DeleteAssignmentRequest} request
     * @param {AssignmentsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.assignments.deleteAssignment({
     *         subject_id: "subject_id"
     *     })
     */
    public deleteAssignment(
        request: BillkitApi.DeleteAssignmentRequest,
        requestOptions?: AssignmentsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteAssignment(request, requestOptions));
    }

    private async __deleteAssignment(
        request: BillkitApi.DeleteAssignmentRequest,
        requestOptions?: AssignmentsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { subject_id: subjectId } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `assignments/${core.url.encodePathParam(subjectId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/assignments/{subject_id}");
    }
}
