// This file was auto-generated by Fern from our API Definition.

/** Supported output formats for schema retrieval/preview. */
export const GetSchemaRequestFormat = {
    Json: "json",
    Yaml: "yaml",
} as const;
export type GetSchemaRequestFormat = (typeof GetSchemaRequestFormat)[keyof typeof GetSchemaRequestFormat];
