// This file was auto-generated by Fern from our API Definition.

/** Supported output formats for schema retrieval/preview. */
export const ValidateSchemaRequestFormat = {
    Json: "json",
    Yaml: "yaml",
} as const;
export type ValidateSchemaRequestFormat =
    (typeof ValidateSchemaRequestFormat)[keyof typeof ValidateSchemaRequestFormat];
