// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as BillkitApi from "../../../index.js";

export declare namespace AddonsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Attach add-ons to subjects
 */
export class AddonsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<AddonsClient.Options>;

    constructor(options: AddonsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Validates that the add-on key exists in the tenant's schema, attaches it to
     * the subject's existing assignment in the store, and invalidates the subject's
     * cache entries.
     *
     * - If the request body is missing or malformed: returns 400 (via Axum rejection).
     * - If subject_id or addon_key is empty: returns 400.
     * - If the tenant has no schema uploaded: returns 422.
     * - If the add-on key does not exist in the schema: returns 422.
     * - If the subject has no existing assignment: returns 404.
     * - If a store or cache error occurs: returns 500.
     * - On success: returns 200 with the updated add-on list.
     *
     * @param {BillkitApi.AttachAddonRequest} request
     * @param {AddonsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.UnauthorizedError}
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.UnprocessableEntityError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.addons.attachAddon({
     *         addon_key: "addon_key",
     *         subject_id: "subject_id"
     *     })
     */
    public attachAddon(
        request: BillkitApi.AttachAddonRequest,
        requestOptions?: AddonsClient.RequestOptions,
    ): core.HttpResponsePromise<BillkitApi.AttachAddonResponse> {
        return core.HttpResponsePromise.fromPromise(this.__attachAddon(request, requestOptions));
    }

    private async __attachAddon(
        request: BillkitApi.AttachAddonRequest,
        requestOptions?: AddonsClient.RequestOptions,
    ): Promise<core.WithRawResponse<BillkitApi.AttachAddonResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                "addons",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BillkitApi.AttachAddonResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BillkitApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BillkitApi.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/addons");
    }

    /**
     * Removes the given add-on from the subject's existing assignment in the store
     * and invalidates the subject's cache entries. Tenant is resolved from
     * `X-Api-Key` via the auth middleware.
     *
     * - If subject_id or addon_key is empty: returns 400.
     * - If the subject has no existing assignment: returns 404.
     * - If a store error occurs: returns 500.
     * - On success: returns 204 No Content, whether or not the add-on was
     *   actually attached (idempotent, matching `DELETE /assignments/{subject_id}`).
     *
     * @param {BillkitApi.DetachAddonRequest} request
     * @param {AddonsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BillkitApi.BadRequestError}
     * @throws {@link BillkitApi.UnauthorizedError}
     * @throws {@link BillkitApi.NotFoundError}
     * @throws {@link BillkitApi.InternalServerError}
     * @throws {@link errors.BillkitApiError}
     * @throws {@link errors.BillkitApiTimeoutError}
     *
     * @example
     *     await client.addons.detachAddon({
     *         subject_id: "subject_id",
     *         addon_key: "addon_key"
     *     })
     */
    public detachAddon(
        request: BillkitApi.DetachAddonRequest,
        requestOptions?: AddonsClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__detachAddon(request, requestOptions));
    }

    private async __detachAddon(
        request: BillkitApi.DetachAddonRequest,
        requestOptions?: AddonsClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { subject_id: subjectId, addon_key: addonKey } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)),
                `subjects/${core.url.encodePathParam(subjectId)}/addons/${core.url.encodePathParam(addonKey)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BillkitApi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new BillkitApi.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BillkitApi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new BillkitApi.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BillkitApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/subjects/{subject_id}/addons/{addon_key}",
        );
    }
}
