// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListInvoiceFailuresRequest {
    /** Filter by subject ID */
    subject_id?: string;
    /** Filter by retry-budget status (true = exhausted) */
    exhausted?: boolean;
    /** Maximum items per page (1–1000, default 100) */
    limit?: number;
    /** Opaque pagination cursor from previous response */
    cursor?: string;
}
