// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListInvoicesRequest {
    /** Filter by subject ID */
    subject_id?: string;
    /** Filter by status (open, paid, past_due, uncollectible) */
    status?: string;
    /** RFC 3339 start date filter */
    start_date?: string;
    /** RFC 3339 end date filter */
    end_date?: string;
    /** Maximum items per page (1–1000, default 100) */
    limit?: number;
    /** Opaque pagination cursor from previous response */
    cursor?: string;
}
