// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListInvoicesRequest {
    /** Filter by subject ID */
    subject_id?: string;
    /** Filter by status (open, paid, past_due, uncollectible) */
    status?: string;
    /** ISO 8601 start date filter */
    start_date?: string;
    /** ISO 8601 end date filter */
    end_date?: string;
}
