// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contract_key: "contract_key",
 *         subject_id: "subject_id"
 *     }
 */
export interface ApplyContractRequest {
    contract_key: string;
    subject_id: string;
}
