// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ApiKeysClient", () => {
    test("list_keys (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            keys: [{ created_at: "created_at", key_id: "key_id", name: "name", prefix: "prefix" }],
        };

        server.mockEndpoint().get("/keys").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.listKeys();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_keys (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/keys").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.listKeys();
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("list_keys (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/keys").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.listKeys();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });

    test("create_key (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = {
            api_key: "api_key",
            created_at: "created_at",
            key_id: "key_id",
            message: "message",
            name: "name",
            prefix: "prefix",
        };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.apiKeys.createKey({
            name: "name",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_key (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.createKey({
                name: "name",
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("create_key (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.createKey({
                name: "name",
            });
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("create_key (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.createKey({
                name: "name",
            });
        }).rejects.toThrow(BillkitApi.ConflictError);
    });

    test("create_key (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "name" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/keys")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.apiKeys.createKey({
                name: "name",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });

    test("rotate_key (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { api_key: "api_key", message: "message" };

        server.mockEndpoint().post("/keys/rotate").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.rotateKey();
        expect(response).toEqual(rawResponseBody);
    });

    test("rotate_key (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/keys/rotate").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.rotateKey();
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("rotate_key (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/keys/rotate").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.rotateKey();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });

    test("delete_key (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { message: "message" };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.apiKeys.deleteKey({
            key_id: "key_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("delete_key (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.deleteKey({
                key_id: "key_id",
            });
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("delete_key (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.deleteKey({
                key_id: "key_id",
            });
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("delete_key (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().delete("/keys/key_id").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.apiKeys.deleteKey({
                key_id: "key_id",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
