// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AssignmentsClient", () => {
    test("create_assignment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { plan_key: "plan_key", subject_id: "subject_id" };
        const rawResponseBody = { assigned_at: "assigned_at", plan_key: "plan_key", subject_id: "subject_id" };

        server
            .mockEndpoint()
            .post("/assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.assignments.createAssignment({
            plan_key: "plan_key",
            subject_id: "subject_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_assignment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { plan_key: "plan_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.createAssignment({
                plan_key: "plan_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("create_assignment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { plan_key: "plan_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.createAssignment({
                plan_key: "plan_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("create_assignment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { plan_key: "plan_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.createAssignment({
                plan_key: "plan_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.ForbiddenError);
    });

    test("create_assignment (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { plan_key: "plan_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.createAssignment({
                plan_key: "plan_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnprocessableEntityError);
    });

    test("create_assignment (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { plan_key: "plan_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/assignments")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.createAssignment({
                plan_key: "plan_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });

    test("delete_assignment (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/assignments/subject_id").respondWith().statusCode(200).build();

        const response = await client.assignments.deleteAssignment({
            subject_id: "subject_id",
        });
        expect(response).toEqual(undefined);
    });

    test("delete_assignment (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/assignments/subject_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.deleteAssignment({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("delete_assignment (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/assignments/subject_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.deleteAssignment({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("delete_assignment (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/assignments/subject_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.assignments.deleteAssignment({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
