// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BillingClient", () => {
    test("create_portal_token (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { expires_at: "expires_at", portal_url: "portal_url", token: "token" };

        server
            .mockEndpoint()
            .post("/billing/portal-token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.billing.createPortalToken({
            subject_id: "subject_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("create_portal_token (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/billing/portal-token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.createPortalToken({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("create_portal_token (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/billing/portal-token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.createPortalToken({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("create_portal_token (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/billing/portal-token")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.billing.createPortalToken({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
