// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ContractsClient", () => {
    test("apply_contract (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { contract_key: "contract_key", subject_id: "subject_id" };
        const rawResponseBody = { contract_key: "contract_key", subject_id: "subject_id" };

        server
            .mockEndpoint()
            .post("/contracts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.contracts.applyContract({
            contract_key: "contract_key",
            subject_id: "subject_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("apply_contract (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { contract_key: "contract_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/contracts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contracts.applyContract({
                contract_key: "contract_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("apply_contract (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { contract_key: "contract_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/contracts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contracts.applyContract({
                contract_key: "contract_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("apply_contract (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { contract_key: "contract_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/contracts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contracts.applyContract({
                contract_key: "contract_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnprocessableEntityError);
    });

    test("apply_contract (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { contract_key: "contract_key", subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/contracts")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.contracts.applyContract({
                contract_key: "contract_key",
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
