// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("InvoicesClient", () => {
    test("list_invoices (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            invoices: [
                {
                    amount_cents: 1000000,
                    billing_period_end: "billing_period_end",
                    billing_period_start: "billing_period_start",
                    created_at: "created_at",
                    currency: "currency",
                    invoice_id: "invoice_id",
                    line_items: [{ amount_cents: 1000000, description: "description" }],
                    paid_at: "paid_at",
                    status: "status",
                    stripe_invoice_id: "stripe_invoice_id",
                    subject_id: "subject_id",
                },
            ],
            total: 1,
        };

        server.mockEndpoint().get("/invoices").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.invoices.listInvoices();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_invoices (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/invoices").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.invoices.listInvoices();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });

    test("preview_invoice (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            base_price_cents: 1000000,
            currency: "currency",
            line_items: [{ amount_cents: 1000000, description: "description" }],
            overage_items: [
                {
                    amount_cents: 1000000,
                    feature_code: "feature_code",
                    limit: 1000000,
                    overage_units: 1000000,
                    unit_price_cents: 1000000,
                    usage: 1000000,
                },
            ],
            plan_key: "plan_key",
            subject_id: "subject_id",
            total_cents: 1000000,
        };

        server
            .mockEndpoint()
            .get("/invoices/subject_id/preview")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.invoices.previewInvoice({
            subject_id: "subject_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("preview_invoice (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/invoices/subject_id/preview")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.invoices.previewInvoice({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("preview_invoice (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/invoices/subject_id/preview")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.invoices.previewInvoice({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnprocessableEntityError);
    });

    test("preview_invoice (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/invoices/subject_id/preview")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.invoices.previewInvoice({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
