// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PricingClient", () => {
    test("get_pricing (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            billing: { billing_cycle: "billing_cycle", currency: "currency" },
            features: [{ code: "code", display_name: "display_name", type: "type" }],
            metadata: { generated_at: "generated_at", schema_version: "schema_version" },
            plans: [
                {
                    display_name: "display_name",
                    feature_values: {},
                    key: "key",
                    price: 1000000,
                    price_display: "price_display",
                },
            ],
            rate_card: {
                dimensions: [
                    {
                        code: "code",
                        display_name: "display_name",
                        free_tier: 1000000,
                        free_tier_display: "free_tier_display",
                        unit_price_cents: 1000000,
                        unit_price_display: "unit_price_display",
                        unit_size: 1000000,
                    },
                ],
            },
        };

        server.mockEndpoint().get("/pricing").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.pricing.getPricing();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_pricing (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/pricing").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pricing.getPricing();
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("get_pricing (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/pricing").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pricing.getPricing();
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("get_pricing (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/pricing").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.pricing.getPricing();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
