// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SchemaClient", () => {
    test("put_schema (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ field: "field", message: "message" }],
            valid: true,
            warnings: [{ field: "field", message: "message" }],
        };

        server.mockEndpoint().put("/schema").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.schema.putSchema();
        expect(response).toEqual(rawResponseBody);
    });

    test("put_schema (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().put("/schema").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.schema.putSchema();
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("put_schema (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().put("/schema").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.schema.putSchema();
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("put_schema (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().put("/schema").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.schema.putSchema();
        }).rejects.toThrow(BillkitApi.ForbiddenError);
    });

    test("put_schema (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().put("/schema").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.schema.putSchema();
        }).rejects.toThrow(BillkitApi.UnprocessableEntityError);
    });

    test("put_schema (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().put("/schema").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.schema.putSchema();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });

    test("validate_schema (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ field: "field", message: "message" }],
            valid: true,
            warnings: [{ field: "field", message: "message" }],
        };

        server.mockEndpoint().post("/schema/validate").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.schema.validateSchema();
        expect(response).toEqual(rawResponseBody);
    });

    test("validate_schema (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/schema/validate").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.schema.validateSchema();
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("validate_schema (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().post("/schema/validate").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.schema.validateSchema();
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });
});
