// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SubjectsClient", () => {
    test("list_subjects (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            has_more: true,
            next_cursor: "next_cursor",
            subjects: [
                {
                    addons: ["addons"],
                    assigned_at: "assigned_at",
                    contract_key: "contract_key",
                    plan_key: "plan_key",
                    subject_id: "subject_id",
                },
            ],
        };

        server.mockEndpoint().get("/subjects").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.subjects.listSubjects();
        expect(response).toEqual(rawResponseBody);
    });

    test("list_subjects (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/subjects").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.subjects.listSubjects();
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("list_subjects (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/subjects").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.subjects.listSubjects();
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("list_subjects (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/subjects").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.subjects.listSubjects();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });

    test("register_subject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = {
            billing_status: "billing_status",
            email: "email",
            name: "name",
            plan_key: "plan_key",
            stripe_customer_id: "stripe_customer_id",
            subject_id: "subject_id",
        };

        server
            .mockEndpoint()
            .post("/subjects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subjects.registerSubject({
            subject_id: "subject_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("register_subject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/subjects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.registerSubject({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("register_subject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/subjects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.registerSubject({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("register_subject (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/subjects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.registerSubject({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnprocessableEntityError);
    });

    test("register_subject (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subject_id: "subject_id" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/subjects")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.registerSubject({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.BadGatewayError);
    });

    test("register_subjects_batch (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subjects: [{ subject_id: "subject_id" }] };
        const rawResponseBody = {
            results: [
                {
                    billing_status: "billing_status",
                    error: "error",
                    stripe_customer_id: "stripe_customer_id",
                    subject_id: "subject_id",
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/subjects/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subjects.registerSubjectsBatch({
            subjects: [
                {
                    subject_id: "subject_id",
                },
            ],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("register_subjects_batch (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subjects: [{ subject_id: "subject_id" }, { subject_id: "subject_id" }] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/subjects/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.registerSubjectsBatch({
                subjects: [
                    {
                        subject_id: "subject_id",
                    },
                    {
                        subject_id: "subject_id",
                    },
                ],
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("register_subjects_batch (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { subjects: [{ subject_id: "subject_id" }, { subject_id: "subject_id" }] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/subjects/batch")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.registerSubjectsBatch({
                subjects: [
                    {
                        subject_id: "subject_id",
                    },
                    {
                        subject_id: "subject_id",
                    },
                ],
            });
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("get_subject (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            addons: ["addons"],
            assigned_at: "assigned_at",
            billing_status: "billing_status",
            contract_key: "contract_key",
            email: "email",
            name: "name",
            payment_method_status: "payment_method_status",
            plan_key: "plan_key",
            stripe_customer_id: "stripe_customer_id",
            subject_id: "subject_id",
        };

        server
            .mockEndpoint()
            .get("/subjects/subject_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.subjects.getSubject({
            subject_id: "subject_id",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("get_subject (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/subjects/subject_id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.getSubject({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("get_subject (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/subjects/subject_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.getSubject({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("get_subject (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/subjects/subject_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.subjects.getSubject({
                subject_id: "subject_id",
            });
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
