// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("TenantsClient", () => {
    test("get_tenant_me (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            created_at: "created_at",
            org_id: "org_id",
            plan_key: "plan_key",
            stripe_customer_id: "stripe_customer_id",
            tenant_id: "tenant_id",
        };

        server.mockEndpoint().get("/tenants/me").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.tenants.getTenantMe();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_tenant_me (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/tenants/me").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tenants.getTenantMe();
        }).rejects.toThrow(BillkitApi.UnauthorizedError);
    });

    test("get_tenant_me (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/tenants/me").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tenants.getTenantMe();
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("get_tenant_me (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/tenants/me").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.tenants.getTenantMe();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
