// This file was auto-generated by Fern from our API Definition.

import * as BillkitApi from "../../src/api/index";
import { BillkitApiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("UsageClient", () => {
    test("set_usage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { value: 1000000 };
        const rawResponseBody = { accepted: true, max: 1000000, new_value: 1000000, previous_value: 1000000 };

        server
            .mockEndpoint()
            .put("/subjects/subject_id/usage/feature_code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.usage.setUsage({
            subject_id: "subject_id",
            feature_code: "feature_code",
            value: 1000000,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("set_usage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { value: 1000000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/subjects/subject_id/usage/feature_code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.usage.setUsage({
                subject_id: "subject_id",
                feature_code: "feature_code",
                value: 1000000,
            });
        }).rejects.toThrow(BillkitApi.BadRequestError);
    });

    test("set_usage (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { value: 1000000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/subjects/subject_id/usage/feature_code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.usage.setUsage({
                subject_id: "subject_id",
                feature_code: "feature_code",
                value: 1000000,
            });
        }).rejects.toThrow(BillkitApi.NotFoundError);
    });

    test("set_usage (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { value: 1000000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/subjects/subject_id/usage/feature_code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.usage.setUsage({
                subject_id: "subject_id",
                feature_code: "feature_code",
                value: 1000000,
            });
        }).rejects.toThrow(BillkitApi.ConflictError);
    });

    test("set_usage (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { value: 1000000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/subjects/subject_id/usage/feature_code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.usage.setUsage({
                subject_id: "subject_id",
                feature_code: "feature_code",
                value: 1000000,
            });
        }).rejects.toThrow(BillkitApi.UnprocessableEntityError);
    });

    test("set_usage (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { value: 1000000 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/subjects/subject_id/usage/feature_code")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.usage.setUsage({
                subject_id: "subject_id",
                feature_code: "feature_code",
                value: 1000000,
            });
        }).rejects.toThrow(BillkitApi.ServiceUnavailableError);
    });

    test("get_usage (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            billing_period_end: "2024-01-15T09:30:00Z",
            billing_period_start: "2024-01-15T09:30:00Z",
            features: [
                {
                    billing_period_usage: 1000000,
                    feature_code: "feature_code",
                    feature_type: "feature_type",
                    resets_at: "2024-01-15T09:30:00Z",
                    total_usage: 1000000,
                    window_end: "2024-01-15T09:30:00Z",
                    window_start: "2024-01-15T09:30:00Z",
                },
            ],
            total_api_calls: 1000000,
        };

        server.mockEndpoint().get("/usage").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.usage.getUsage();
        expect(response).toEqual(rawResponseBody);
    });

    test("get_usage (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BillkitApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/usage").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.usage.getUsage();
        }).rejects.toThrow(BillkitApi.InternalServerError);
    });
});
