// This file was auto-generated by Fern from our API Definition.

import { AddonsClient } from "./api/resources/addons/client/Client.js";
import { ApiKeysClient } from "./api/resources/apiKeys/client/Client.js";
import { AssignmentsClient } from "./api/resources/assignments/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { ContractsClient } from "./api/resources/contracts/client/Client.js";
import { EntitlementsClient } from "./api/resources/entitlements/client/Client.js";
import { InvoicesClient } from "./api/resources/invoices/client/Client.js";
import { PricingClient } from "./api/resources/pricing/client/Client.js";
import { SchemaClient } from "./api/resources/schema/client/Client.js";
import { SubjectsClient } from "./api/resources/subjects/client/Client.js";
import { TenantsClient } from "./api/resources/tenants/client/Client.js";
import { UsageClient } from "./api/resources/usage/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace BillkitApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BillkitApiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BillkitApiClient.Options>;
    protected _addons: AddonsClient | undefined;
    protected _assignments: AssignmentsClient | undefined;
    protected _billing: BillingClient | undefined;
    protected _entitlements: EntitlementsClient | undefined;
    protected _contracts: ContractsClient | undefined;
    protected _invoices: InvoicesClient | undefined;
    protected _apiKeys: ApiKeysClient | undefined;
    protected _pricing: PricingClient | undefined;
    protected _schema: SchemaClient | undefined;
    protected _subjects: SubjectsClient | undefined;
    protected _usage: UsageClient | undefined;
    protected _tenants: TenantsClient | undefined;

    constructor(options: BillkitApiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get addons(): AddonsClient {
        return (this._addons ??= new AddonsClient(this._options));
    }

    public get assignments(): AssignmentsClient {
        return (this._assignments ??= new AssignmentsClient(this._options));
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get entitlements(): EntitlementsClient {
        return (this._entitlements ??= new EntitlementsClient(this._options));
    }

    public get contracts(): ContractsClient {
        return (this._contracts ??= new ContractsClient(this._options));
    }

    public get invoices(): InvoicesClient {
        return (this._invoices ??= new InvoicesClient(this._options));
    }

    public get apiKeys(): ApiKeysClient {
        return (this._apiKeys ??= new ApiKeysClient(this._options));
    }

    public get pricing(): PricingClient {
        return (this._pricing ??= new PricingClient(this._options));
    }

    public get schema(): SchemaClient {
        return (this._schema ??= new SchemaClient(this._options));
    }

    public get subjects(): SubjectsClient {
        return (this._subjects ??= new SubjectsClient(this._options));
    }

    public get usage(): UsageClient {
        return (this._usage ??= new UsageClient(this._options));
    }

    public get tenants(): TenantsClient {
        return (this._tenants ??= new TenantsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
