// This file was auto-generated by Fern from our API Definition.

import type * as BillkitApi from "../../../../index.js";

/**
 * @example
 *     {
 *         subjects: [{
 *                 subject_id: "subject_id"
 *             }]
 *     }
 */
export interface BatchRegisterRequest {
    subjects: BillkitApi.RegisterSubjectRequest[];
}
