// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subject_id: "subject_id"
 *     }
 */
export interface GetSubjectRequest {
    /** The subject identifier */
    subject_id: string;
}
